# Generated by Django 5.2.5 on 2025-12-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='vat_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
    ]
