# Generated by Django 5.2.5 on 2026-01-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_account_name_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='bank_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='cash_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_source',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
