# Generated by Django 5.2.5 on 2026-02-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_account_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/'),
        ),
    ]
