# Generated by Django 5.2.5 on 2026-02-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expense_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vat_enabled',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vat_rate',
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
