# Generated by Django 5.2.5 on 2026-02-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_account_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('combined', 'Both / Combined')], db_index=True, max_length=10, unique=True),
        ),
    ]
