# Generated by Django 5.2.5 on 2026-02-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_source',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('combined', 'Both / Combined')], db_index=True, max_length=10),
        ),
    ]
