# Generated by Django 5.2.5 on 2026-02-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
    ]
