# Generated by Django 5.2.5 on 2026-01-19 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0004_remove_expense_bank_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('income_type', models.CharField(choices=[('MONTHLY_FEE', 'Monthly Parent Fee'), ('REGISTRATION', 'Registration Fee'), ('DONATION', 'Donation'), ('OTHER', 'Other Income')], max_length=30)),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.account')),
            ],
        ),
    ]
