# Generated by Django 5.2.5 on 2026-02-14 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_expense_bank_amount_and_more'),
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('MONTHLY_FEE', 'Monthly Parent Fee'), ('REGISTRATION', 'Registration Fee'), ('DONATION', 'Donation'), ('OTHER', 'Other Income')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='expenses.account'),
        ),
    ]
