# Generated by Django 5.2.5 on 2026-02-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_alter_income_options_alter_income_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='income',
            name='income_type',
        ),
        migrations.RemoveField(
            model_name='income',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='income',
            name='payment_destination',
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('sales', 'Sales'), ('investment', 'Investment'), ('other', 'Other')], db_index=True, default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='payment_source',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('combined', 'Both / Combined')], db_index=True, default='sss', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(),
        ),
    ]
