# Generated by Django 5.2.5 on 2026-02-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0003_alter_income_options_remove_income_income_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='amount_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='income',
            name='amount_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
