# Generated by Django 5.2.5 on 2026-03-05 11:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0004_income_amount_bank_income_amount_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='income',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='income',
            name='due_date',
            field=models.DateField(blank=True, help_text='Important for receivable or liability', null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='payer_name',
            field=models.CharField(blank=True, help_text='Parent name or organization', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='income',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('receivable', 'Receivable'), ('liability', 'Liability')], db_index=True, default='income', max_length=20),
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('tuition_fee', 'Child Tuition Fee'), ('registration_fee', 'Registration Fee'), ('late_fee', 'Late Payment Fee'), ('meal_fee', 'Meal Fee'), ('activity_fee', 'Activity Fee'), ('donation', 'Donation'), ('sales', 'Sales'), ('investment', 'Investment'), ('other', 'Other Income')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_source',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('combined', 'Combined')], db_index=True, max_length=10),
        ),
    ]
